name: Build and Push to GitVerse Registry

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push with Kaniko
        uses: docker://gcr.io/kaniko-project/executor:v1.24.0
        with:
          args: >
            --context=./log_ai_agent
            --dockerfile=./log_ai_agent/Dockerfile
            --destination=gitverse.ru/litsu/ai-cyberlogagent:latest
            --destination=gitverse.ru/litsu/ai-cyberlogagent:${{ gitverse.run_number }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /kaniko/service-account