"""Prompt templates for log analysis."""

from .log_analysis import (
    FINAL_REPORT_USER_PROMPT,
    PRIMARY_ANALYSIS_USER_PROMPT_V2,
    SUMMARIZER_USER_PROMPT,
)
from .system import (
    FINAL_REPORT_SYSTEM_PROMPT,
    PRIMARY_ANALYSIS_SYSTEM_PROMPT,
    SUMMARIZER_SYSTEM_PROMPT,
)

__all__ = [
    "PRIMARY_ANALYSIS_SYSTEM_PROMPT",
    "FINAL_REPORT_SYSTEM_PROMPT",
    "SUMMARIZER_SYSTEM_PROMPT",
    "PRIMARY_ANALYSIS_USER_PROMPT_V2",
    "FINAL_REPORT_USER_PROMPT",
    "SUMMARIZER_USER_PROMPT",
]
