FROM timberio/vector:0.39.0-debian

RUN mkdir -p /etc/vector/lua /data/external /data/processed/collected_logs /var/lib/vector

COPY vector/vector.toml /etc/vector/vector.toml
COPY vector/lua/chunk_logs.lua /etc/vector/lua/chunk_logs.lua

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["vector", "--config", "/etc/vector/vector.toml"]